
# html lang
language: en

# Miscelaneous
favicon: /source/favicon.ico

# head-bg 头像背景图 
headbg: https://moumao.moumaobuchiyu.com/images/head-bg.jpg

# header 头像图 
header: https://moumao.moumaobuchiyu.com/images/header.jpg

# post-header 标语部分
post_header:
  img: https://moumao.moumaobuchiyu.com/images/coverpic.jpg
  about:
    - "腹有诗书气自华"
  url: "http://moumaobuchiyu.com"

#链接
sns:
    github: "https://github.com/moumao"
    weibo: "http://weibo.com/u/3168872804"
    zhihu: "https://www.zhihu.com/people/mou-mao-75/activities"
    douban:
    email: "1195358569@qq.com"

#默认thumbnail图片的数目
thumbnail: 19

#访客
visitor: false

#nav
sidebar:
    homepage:
        use: true
    archives:
        use: true
    categories:
        use: true
    tags:
        use: true
    about:
        use: true
    friends:
        use: true
    photo:
        use: true

# Reading experience
reading:
    entry_excerpt: 100

#photo page
photo:
    name: "某猫の影集"
    about: "希望 你会 喜欢我拍的照片"

# stylesheets loaded in the <head>
stylesheets:
  - https://cdn.bootcss.com/materialize/0.98.2/css/materialize.min.css
  - /css/Vateral.min.css

# scripts loaded in the end of the body
scripts:
  - https://cdn.bootcss.com/jquery/3.2.0/jquery.min.js
  - https://moumao.moumaobuchiyu.com/js/materialize.min.js
  - https://moumao.moumaobuchiyu.com/js/lazyload.min.js
  - https://moumao.moumaobuchiyu.com/js/jquery.rotate.min.js
  - https://moumao.moumaobuchiyu.com/js/Vateral.min.js


