
# html lang
language: en

# Miscelaneous
favicon: /source/favicon.ico

# head-bg 头像背景图 
headbg: https://moumao.moumaobuchiyu.com/images/head-bg.jpg

# header 头像图 
header: https://moumao.moumaobuchiyu.com/images/header.jpg

# post-header 标语部分
post_header:
  img: https://moumao.moumaobuchiyu.com/images/coverpic.jpg
  about:
    - "您好 欢迎使用Vateral主题"
  url: "http://example.com"

#链接
sns:
    github: "http://example.com"
    weibo: "http://example.com"
    zhihu: "http://example.com"
    douban: "http://example.com"

#默认thumbnail图片的数目
thumbnail: 19

#访客
visitor: false

#nav
sidebar:
    homepage:
        use: true
    archives:
        use: true
    categories:
        use: true
    tags:
        use: true
    about:
        use: false
    friends:
        use: false
    photo:
        use: false

# Reading experience
reading:
    entry_excerpt: 100

#photo page
photo:
    name: "影集名称"
    about: "影集简介"

# stylesheets loaded in the <head>
stylesheets:
  - https://cdn.bootcss.com/materialize/0.98.2/css/materialize.min.css
  - /css/Vateral.min.css

# scripts loaded in the end of the body
scripts:
  - https://cdn.bootcss.com/jquery/3.2.0/jquery.min.js
  - https://moumao.moumaobuchiyu.com/js/materialize.min.js
  - https://moumao.moumaobuchiyu.com/js/lazyload.min.js
  - https://moumao.moumaobuchiyu.com/js/jquery.rotate.min.js
  - //dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js
  - https://moumao.moumaobuchiyu.com/js/Vateral.min.js


