
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives
  Photo: /photo

# Miscelaneous
favicon: /source/favicon.ico

# head-bg 头像背景图
headbg: /images/head-bg.jpg

# header 头像图
header: /images/header.jpg

# post-header
post_header:
  img: /images/coverpic.jpg
  about:
    - "腹有诗书气自华"
  url: "http://www.moumaobuchiyu.com"

#链接
sns:
    github: "https://github.com/moumao"
    email: "https://1195358569@qq.com"
    facebook:
    weibo: "http://weibo.com/u/3168872804"
    rss:
    douban:

#默认thumbnail的数目
thumbnail: 19


#nav
sidebar:
    homepage:
        use: true
        divider: false
    archives:
        use: true
        divider: false
    categories:
        use: true
        divider: false
    about:
        use: true
        divider: false
    tags:
        use: true
        divider: false
    pages:

    article_num:
        use: false
        divider: false

# Reading experience
reading:
    entry_excerpt: 100

# stylesheets loaded in the <head>
stylesheets:
  - /css/materialize.min.css
  - /css/Vateral.css

# scripts loaded in the end of the body
scripts:
  - https://apps.bdimg.com/libs/jquery/1.10.2/jquery.min.js
  - /js/materialize.min.js
  - /js/jquery.rotate.min.js
  - /js/lazyload.min.js
  - /js/Vateral.js


