
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives
  Photo: /photo

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/Vateral.css

# scripts loaded in the end of the body
scripts:
- http://code.jquery.com/jquery.min.js
- /js/jquery.rotate.min.js
- /js/Vateral.js

