
# html lang
language: en

# Miscelaneous
favicon: /source/favicon.ico

# head-bg 头像背景图 
headbg: /images/head-bg.jpg
# header 头像图 
header: /images/header.jpg

# post-header 标语部分
post_header:
  img: /images/coverpic.jpg
  about:
    - "你好啊 欢迎来到本站"
  url: "http://example.com"

#链接
sns:
    github: "http://example.com"
    weibo: "http://example.com"
    zhihu: "http://example.com"
    twitter: "http://example.com"
    email: "http://example.com"

#默认thumbnail图片的数目
thumbnail: 19

#访客
visitor: false

#nav
sidebar:
    homepage:
        use: true
    archives:
        use: true
    categories:
        use: true
    tags:
        use: false
    about:
        use: false
    friends:
        use: false
    photo:
        use: false

# Reading experience
reading:
    entry_excerpt: 100

#photo page
photo:
    name: "影集名称"
    about: "影集简介"

# stylesheets loaded in the <head>
stylesheets:
  - http://cdn.bootcss.com/materialize/0.98.2/css/materialize.min.css
  - /css/Vateral.min.css

# scripts loaded in the end of the body
scripts:
  - http://cdn.bootcss.com/jquery/3.2.1/jquery.min.js
  - http://cdn.bootcss.com/materialize/0.98.2/js/materialize.min.js
  - http://cdn.bootcss.com/jquery_lazyload/1.9.6/jquery.lazyload.min.js
  - /js/jquery.rotate.min.js
  - /js/Vateral.min.js


